---
apiVersion: v1
kind: Secret
metadata:
  name: backend-redis
stringData:
  REDIS_STORAGE_URL: "redis://3scale:redhat@redis-5:6379/0"
  REDIS_QUEUES_URL: "redis://3scale:redhat@redis-5:6379/1"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: system-database
stringData:
  URL: "postgresql://postgres:r4m4lh0@3.23.29.220:5432/system"
  DB_USER: "postgres"
  DB_PASSWORD: "r4m4lh0"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: system-redis
stringData:
  URL: "redis://3scale:redhat@redis-5:6379/2"
  MESSAGE_BUS_URL: "redis://3scale:redhat@redis-5:6379/8"
type: Opaque
