apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: 3scale
spec:
  wildcardDomain: apps.cluster-dc51.dc51.sandbox810.opentlc.com
  resourceRequirementsEnabled: false
  monitoring:
    enabled: true
