apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: 3scale
spec:
  wildcardDomain: apps.cluster-5f88.5f88.sandbox1482.opentlc.com
  resourceRequirementsEnabled: false
  monitoring:
    enabled: true
